services:
  bamboo:
    image: bamboo-server:9.6.5
    container_name: bamboo-srv
    hostname: bamboo-server
    environment:
      - TZ=Asia/Bangkok
    #      - JVM_MINIMUM_MEMORY=1g
    #      - JVM_MAXIMUM_MEMORY=12g
    #      - JVM_CODE_CACHE_ARGS='-XX:InitialCodeCacheSize=1g -XX:ReservedCodeCacheSize=8g'
    depends_on:
      - mysql
    ports:
      - "8085:8085"
      - "54663:54663"
    volumes:
      - home_data:/var/atlassian/application-data/bamboo
    restart: always
    networks:
      - network-bridge

  mysql:
    image: mysql:8.0
    container_name: mysql-bamboo
    environment:
      - TZ=Asia/Bangkok
      - MYSQL_DATABASE=bamboodb
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=bamboouser
      - MYSQL_PASSWORD=123123
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin', '--transaction-isolation=READ-COMMITTED', '--innodb_log_file_size=256M', '--max_allowed_packet=256M','--log_bin_trust_function_creators=1']
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - network-bridge

networks:
  network-bridge:
    driver: bridge

volumes:
  home_data:
    external: false
  mysql_data:
    external: false